# .goreleaser.yaml
version: 2

project_name: envy

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/main.go
    binary: envy
    ldflags:
      - -s -w

archives:
  - format: tar.gz
    # Name template to match install.sh expectation: envy_1.0.0_linux_amd64.tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    # Wrap in directory? install.sh handles both, but usually cleaner to verify if files are at root or nested.
    # install.sh uses `tar -xzf ... -C tmp_dir` and then `find` to locate binary.
    # Standard GoReleaser behavior (files in root of archive) is fine.

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
